package pl.pje.jprogs.rod_entity;
// Generated 2013-09-08 22:11:50 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PjrodFaktura generated by hbm2java
 */
@Entity
@Table(name="pjrod_faktura"
    ,catalog="rod"
)
public class PjrodFaktura  implements java.io.Serializable {


     private Integer idFaktura;
     private String nrFak;
     private int nrLicznika;
     private int opsPrzejsciowa;
     private int opsPrzesyl;
     private int opsDystrybucja;
     private int opzEnergia;
     private int opzSkljak;
     private int opzSieciowa;
     private int dataOd;
     private int dataDo;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodFaktura() {
    }

	
    public PjrodFaktura(String nrFak, int nrLicznika, int opsPrzejsciowa, int opsPrzesyl, int opsDystrybucja, int opzEnergia, int opzSkljak, int opzSieciowa, int dataOd, int dataDo, int created, int lastMod) {
        this.nrFak = nrFak;
        this.nrLicznika = nrLicznika;
        this.opsPrzejsciowa = opsPrzejsciowa;
        this.opsPrzesyl = opsPrzesyl;
        this.opsDystrybucja = opsDystrybucja;
        this.opzEnergia = opzEnergia;
        this.opzSkljak = opzSkljak;
        this.opzSieciowa = opzSieciowa;
        this.dataOd = dataOd;
        this.dataDo = dataDo;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodFaktura(String nrFak, int nrLicznika, int opsPrzejsciowa, int opsPrzesyl, int opsDystrybucja, int opzEnergia, int opzSkljak, int opzSieciowa, int dataOd, int dataDo, int created, int lastMod, String whoMod) {
       this.nrFak = nrFak;
       this.nrLicznika = nrLicznika;
       this.opsPrzejsciowa = opsPrzejsciowa;
       this.opsPrzesyl = opsPrzesyl;
       this.opsDystrybucja = opsDystrybucja;
       this.opzEnergia = opzEnergia;
       this.opzSkljak = opzSkljak;
       this.opzSieciowa = opzSieciowa;
       this.dataOd = dataOd;
       this.dataDo = dataDo;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_faktura", unique=true, nullable=false)
    public Integer getIdFaktura() {
        return this.idFaktura;
    }
    
    public void setIdFaktura(Integer idFaktura) {
        this.idFaktura = idFaktura;
    }
    
    @Column(name="nr_fak", nullable=false, length=64)
    public String getNrFak() {
        return this.nrFak;
    }
    
    public void setNrFak(String nrFak) {
        this.nrFak = nrFak;
    }
    
    @Column(name="nr_licznika", nullable=false)
    public int getNrLicznika() {
        return this.nrLicznika;
    }
    
    public void setNrLicznika(int nrLicznika) {
        this.nrLicznika = nrLicznika;
    }
    
    @Column(name="ops_przejsciowa", nullable=false)
    public int getOpsPrzejsciowa() {
        return this.opsPrzejsciowa;
    }
    
    public void setOpsPrzejsciowa(int opsPrzejsciowa) {
        this.opsPrzejsciowa = opsPrzejsciowa;
    }
    
    @Column(name="ops_przesyl", nullable=false)
    public int getOpsPrzesyl() {
        return this.opsPrzesyl;
    }
    
    public void setOpsPrzesyl(int opsPrzesyl) {
        this.opsPrzesyl = opsPrzesyl;
    }
    
    @Column(name="ops_dystrybucja", nullable=false)
    public int getOpsDystrybucja() {
        return this.opsDystrybucja;
    }
    
    public void setOpsDystrybucja(int opsDystrybucja) {
        this.opsDystrybucja = opsDystrybucja;
    }
    
    @Column(name="opz_energia", nullable=false)
    public int getOpzEnergia() {
        return this.opzEnergia;
    }
    
    public void setOpzEnergia(int opzEnergia) {
        this.opzEnergia = opzEnergia;
    }
    
    @Column(name="opz_skljak", nullable=false)
    public int getOpzSkljak() {
        return this.opzSkljak;
    }
    
    public void setOpzSkljak(int opzSkljak) {
        this.opzSkljak = opzSkljak;
    }
    
    @Column(name="opz_sieciowa", nullable=false)
    public int getOpzSieciowa() {
        return this.opzSieciowa;
    }
    
    public void setOpzSieciowa(int opzSieciowa) {
        this.opzSieciowa = opzSieciowa;
    }
    
    @Column(name="data_od", nullable=false)
    public int getDataOd() {
        return this.dataOd;
    }
    
    public void setDataOd(int dataOd) {
        this.dataOd = dataOd;
    }
    
    @Column(name="data_do", nullable=false)
    public int getDataDo() {
        return this.dataDo;
    }
    
    public void setDataDo(int dataDo) {
        this.dataDo = dataDo;
    }
    
    @Column(name="created", nullable=false)
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    
    @Column(name="last_mod", nullable=false)
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    
    @Column(name="who_mod", length=128)
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


