package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodTaryfa generated by hbm2java
 */
public class PjrodTaryfa  implements java.io.Serializable {


     private Integer idTaryfa;
     private String nazwa;
     private int opsPrzejsciowa;
     private int opsPrzesyl;
     private int opsDystrybucja;
     private int opzEnergia;
     private int opzSkljak;
     private int vat1;
     private int vat2;
     private int vatMaska;
     private int opzSieciowa;
     private int dataOd;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodTaryfa() {
    }

	
    public PjrodTaryfa(String nazwa, int opsPrzejsciowa, int opsPrzesyl, int opsDystrybucja, int opzEnergia, int opzSkljak, int vat1, int vat2, int vatMaska, int opzSieciowa, int dataOd, int created, int lastMod) {
        this.nazwa = nazwa;
        this.opsPrzejsciowa = opsPrzejsciowa;
        this.opsPrzesyl = opsPrzesyl;
        this.opsDystrybucja = opsDystrybucja;
        this.opzEnergia = opzEnergia;
        this.opzSkljak = opzSkljak;
        this.vat1 = vat1;
        this.vat2 = vat2;
        this.vatMaska = vatMaska;
        this.opzSieciowa = opzSieciowa;
        this.dataOd = dataOd;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodTaryfa(String nazwa, int opsPrzejsciowa, int opsPrzesyl, int opsDystrybucja, int opzEnergia, int opzSkljak, int vat1, int vat2, int vatMaska, int opzSieciowa, int dataOd, int created, int lastMod, String whoMod) {
       this.nazwa = nazwa;
       this.opsPrzejsciowa = opsPrzejsciowa;
       this.opsPrzesyl = opsPrzesyl;
       this.opsDystrybucja = opsDystrybucja;
       this.opzEnergia = opzEnergia;
       this.opzSkljak = opzSkljak;
       this.vat1 = vat1;
       this.vat2 = vat2;
       this.vatMaska = vatMaska;
       this.opzSieciowa = opzSieciowa;
       this.dataOd = dataOd;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdTaryfa() {
        return this.idTaryfa;
    }
    
    public void setIdTaryfa(Integer idTaryfa) {
        this.idTaryfa = idTaryfa;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public int getOpsPrzejsciowa() {
        return this.opsPrzejsciowa;
    }
    
    public void setOpsPrzejsciowa(int opsPrzejsciowa) {
        this.opsPrzejsciowa = opsPrzejsciowa;
    }
    public int getOpsPrzesyl() {
        return this.opsPrzesyl;
    }
    
    public void setOpsPrzesyl(int opsPrzesyl) {
        this.opsPrzesyl = opsPrzesyl;
    }
    public int getOpsDystrybucja() {
        return this.opsDystrybucja;
    }
    
    public void setOpsDystrybucja(int opsDystrybucja) {
        this.opsDystrybucja = opsDystrybucja;
    }
    public int getOpzEnergia() {
        return this.opzEnergia;
    }
    
    public void setOpzEnergia(int opzEnergia) {
        this.opzEnergia = opzEnergia;
    }
    public int getOpzSkljak() {
        return this.opzSkljak;
    }
    
    public void setOpzSkljak(int opzSkljak) {
        this.opzSkljak = opzSkljak;
    }
    public int getVat1() {
        return this.vat1;
    }
    
    public void setVat1(int vat1) {
        this.vat1 = vat1;
    }
    public int getVat2() {
        return this.vat2;
    }
    
    public void setVat2(int vat2) {
        this.vat2 = vat2;
    }
    public int getVatMaska() {
        return this.vatMaska;
    }
    
    public void setVatMaska(int vatMaska) {
        this.vatMaska = vatMaska;
    }
    public int getOpzSieciowa() {
        return this.opzSieciowa;
    }
    
    public void setOpzSieciowa(int opzSieciowa) {
        this.opzSieciowa = opzSieciowa;
    }
    public int getDataOd() {
        return this.dataOd;
    }
    
    public void setDataOd(int dataOd) {
        this.dataOd = dataOd;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


