package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodDzialkowiec generated by hbm2java
 */
public class PjrodDzialkowiec  implements java.io.Serializable {


     private Integer idDzialkowiec;
     private int idDzialka;
     private String imie;
     private String nazwisko;
     private String adrMiejscowosc;
     private String adrUlica;
     private String adrNrbudynku;
     private String adrNrlokalu;
     private String telefon1;
     private String telefon2;
     private String email;
     private String info;
     private int aktywny;
     private int aktywnyOd;
     private int aktywnyDo;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodDzialkowiec() {
    }

	
    public PjrodDzialkowiec(int idDzialka, String nazwisko, int aktywny, int aktywnyOd, int aktywnyDo, int created, int lastMod) {
        this.idDzialka = idDzialka;
        this.nazwisko = nazwisko;
        this.aktywny = aktywny;
        this.aktywnyOd = aktywnyOd;
        this.aktywnyDo = aktywnyDo;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodDzialkowiec(int idDzialka, String imie, String nazwisko, String adrMiejscowosc, String adrUlica, String adrNrbudynku, String adrNrlokalu, String telefon1, String telefon2, String email, String info, int aktywny, int aktywnyOd, int aktywnyDo, int created, int lastMod, String whoMod) {
       this.idDzialka = idDzialka;
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.adrMiejscowosc = adrMiejscowosc;
       this.adrUlica = adrUlica;
       this.adrNrbudynku = adrNrbudynku;
       this.adrNrlokalu = adrNrlokalu;
       this.telefon1 = telefon1;
       this.telefon2 = telefon2;
       this.email = email;
       this.info = info;
       this.aktywny = aktywny;
       this.aktywnyOd = aktywnyOd;
       this.aktywnyDo = aktywnyDo;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdDzialkowiec() {
        return this.idDzialkowiec;
    }
    
    public void setIdDzialkowiec(Integer idDzialkowiec) {
        this.idDzialkowiec = idDzialkowiec;
    }
    public int getIdDzialka() {
        return this.idDzialka;
    }
    
    public void setIdDzialka(int idDzialka) {
        this.idDzialka = idDzialka;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public String getAdrMiejscowosc() {
        return this.adrMiejscowosc;
    }
    
    public void setAdrMiejscowosc(String adrMiejscowosc) {
        this.adrMiejscowosc = adrMiejscowosc;
    }
    public String getAdrUlica() {
        return this.adrUlica;
    }
    
    public void setAdrUlica(String adrUlica) {
        this.adrUlica = adrUlica;
    }
    public String getAdrNrbudynku() {
        return this.adrNrbudynku;
    }
    
    public void setAdrNrbudynku(String adrNrbudynku) {
        this.adrNrbudynku = adrNrbudynku;
    }
    public String getAdrNrlokalu() {
        return this.adrNrlokalu;
    }
    
    public void setAdrNrlokalu(String adrNrlokalu) {
        this.adrNrlokalu = adrNrlokalu;
    }
    public String getTelefon1() {
        return this.telefon1;
    }
    
    public void setTelefon1(String telefon1) {
        this.telefon1 = telefon1;
    }
    public String getTelefon2() {
        return this.telefon2;
    }
    
    public void setTelefon2(String telefon2) {
        this.telefon2 = telefon2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public int getAktywny() {
        return this.aktywny;
    }
    
    public void setAktywny(int aktywny) {
        this.aktywny = aktywny;
    }
    public int getAktywnyOd() {
        return this.aktywnyOd;
    }
    
    public void setAktywnyOd(int aktywnyOd) {
        this.aktywnyOd = aktywnyOd;
    }
    public int getAktywnyDo() {
        return this.aktywnyDo;
    }
    
    public void setAktywnyDo(int aktywnyDo) {
        this.aktywnyDo = aktywnyDo;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


