package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodFundusz generated by hbm2java
 */
public class PjrodFundusz  implements java.io.Serializable {


     private Integer idFundusz;
     private String nazwaSkr;
     private String nazwa;
     private String opis;
     private String kontoBank;
     private String kontoZpk;
     private int kwota;
     private int domyslny;
     private int dataOd;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodFundusz() {
    }

	
    public PjrodFundusz(String nazwaSkr, String nazwa, int kwota, int domyslny, int dataOd, int created, int lastMod) {
        this.nazwaSkr = nazwaSkr;
        this.nazwa = nazwa;
        this.kwota = kwota;
        this.domyslny = domyslny;
        this.dataOd = dataOd;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodFundusz(String nazwaSkr, String nazwa, String opis, String kontoBank, String kontoZpk, int kwota, int domyslny, int dataOd, int created, int lastMod, String whoMod) {
       this.nazwaSkr = nazwaSkr;
       this.nazwa = nazwa;
       this.opis = opis;
       this.kontoBank = kontoBank;
       this.kontoZpk = kontoZpk;
       this.kwota = kwota;
       this.domyslny = domyslny;
       this.dataOd = dataOd;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdFundusz() {
        return this.idFundusz;
    }
    
    public void setIdFundusz(Integer idFundusz) {
        this.idFundusz = idFundusz;
    }
    public String getNazwaSkr() {
        return this.nazwaSkr;
    }
    
    public void setNazwaSkr(String nazwaSkr) {
        this.nazwaSkr = nazwaSkr;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public String getKontoBank() {
        return this.kontoBank;
    }
    
    public void setKontoBank(String kontoBank) {
        this.kontoBank = kontoBank;
    }
    public String getKontoZpk() {
        return this.kontoZpk;
    }
    
    public void setKontoZpk(String kontoZpk) {
        this.kontoZpk = kontoZpk;
    }
    public int getKwota() {
        return this.kwota;
    }
    
    public void setKwota(int kwota) {
        this.kwota = kwota;
    }
    public int getDomyslny() {
        return this.domyslny;
    }
    
    public void setDomyslny(int domyslny) {
        this.domyslny = domyslny;
    }
    public int getDataOd() {
        return this.dataOd;
    }
    
    public void setDataOd(int dataOd) {
        this.dataOd = dataOd;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


