package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodSala generated by hbm2java
 */
public class PjrodSala  implements java.io.Serializable {


     private Integer idSala;
     private String nazwa;
     private String adres;
     private String opis;
     private String atrybuty;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodSala() {
    }

	
    public PjrodSala(String nazwa, int created, int lastMod) {
        this.nazwa = nazwa;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodSala(String nazwa, String adres, String opis, String atrybuty, int created, int lastMod, String whoMod) {
       this.nazwa = nazwa;
       this.adres = adres;
       this.opis = opis;
       this.atrybuty = atrybuty;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(Integer idSala) {
        this.idSala = idSala;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public String getAtrybuty() {
        return this.atrybuty;
    }
    
    public void setAtrybuty(String atrybuty) {
        this.atrybuty = atrybuty;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


