package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodRezerwacja generated by hbm2java
 */
public class PjrodRezerwacja  implements java.io.Serializable {


     private Integer idRezerwacja;
     private int idSala;
     private String opis;
     private String kto;
     private String haslo;
     private String kontakt;
     private int dataRezerwacji;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodRezerwacja() {
    }

	
    public PjrodRezerwacja(int idSala, String kto, String haslo, String kontakt, int dataRezerwacji, int created, int lastMod) {
        this.idSala = idSala;
        this.kto = kto;
        this.haslo = haslo;
        this.kontakt = kontakt;
        this.dataRezerwacji = dataRezerwacji;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodRezerwacja(int idSala, String opis, String kto, String haslo, String kontakt, int dataRezerwacji, int created, int lastMod, String whoMod) {
       this.idSala = idSala;
       this.opis = opis;
       this.kto = kto;
       this.haslo = haslo;
       this.kontakt = kontakt;
       this.dataRezerwacji = dataRezerwacji;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdRezerwacja() {
        return this.idRezerwacja;
    }
    
    public void setIdRezerwacja(Integer idRezerwacja) {
        this.idRezerwacja = idRezerwacja;
    }
    public int getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(int idSala) {
        this.idSala = idSala;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public String getKto() {
        return this.kto;
    }
    
    public void setKto(String kto) {
        this.kto = kto;
    }
    public String getHaslo() {
        return this.haslo;
    }
    
    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }
    public String getKontakt() {
        return this.kontakt;
    }
    
    public void setKontakt(String kontakt) {
        this.kontakt = kontakt;
    }
    public int getDataRezerwacji() {
        return this.dataRezerwacji;
    }
    
    public void setDataRezerwacji(int dataRezerwacji) {
        this.dataRezerwacji = dataRezerwacji;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


