package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodSektor generated by hbm2java
 */
public class PjrodSektor  implements java.io.Serializable {


     private Integer idSektor;
     private int numer;
     private int idLicznikp;
     private int idLicznikw;
     private int metraz;
     private String zabudowy;
     private String problemy;
     private String adres;
     private String gospodarz;
     private String dozrobienia;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodSektor() {
    }

	
    public PjrodSektor(int numer, int idLicznikp, int idLicznikw, int metraz, int created, int lastMod) {
        this.numer = numer;
        this.idLicznikp = idLicznikp;
        this.idLicznikw = idLicznikw;
        this.metraz = metraz;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodSektor(int numer, int idLicznikp, int idLicznikw, int metraz, String zabudowy, String problemy, String adres, String gospodarz, String dozrobienia, int created, int lastMod, String whoMod) {
       this.numer = numer;
       this.idLicznikp = idLicznikp;
       this.idLicznikw = idLicznikw;
       this.metraz = metraz;
       this.zabudowy = zabudowy;
       this.problemy = problemy;
       this.adres = adres;
       this.gospodarz = gospodarz;
       this.dozrobienia = dozrobienia;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdSektor() {
        return this.idSektor;
    }
    
    public void setIdSektor(Integer idSektor) {
        this.idSektor = idSektor;
    }
    public int getNumer() {
        return this.numer;
    }
    
    public void setNumer(int numer) {
        this.numer = numer;
    }
    public int getIdLicznikp() {
        return this.idLicznikp;
    }
    
    public void setIdLicznikp(int idLicznikp) {
        this.idLicznikp = idLicznikp;
    }
    public int getIdLicznikw() {
        return this.idLicznikw;
    }
    
    public void setIdLicznikw(int idLicznikw) {
        this.idLicznikw = idLicznikw;
    }
    public int getMetraz() {
        return this.metraz;
    }
    
    public void setMetraz(int metraz) {
        this.metraz = metraz;
    }
    public String getZabudowy() {
        return this.zabudowy;
    }
    
    public void setZabudowy(String zabudowy) {
        this.zabudowy = zabudowy;
    }
    public String getProblemy() {
        return this.problemy;
    }
    
    public void setProblemy(String problemy) {
        this.problemy = problemy;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public String getGospodarz() {
        return this.gospodarz;
    }
    
    public void setGospodarz(String gospodarz) {
        this.gospodarz = gospodarz;
    }
    public String getDozrobienia() {
        return this.dozrobienia;
    }
    
    public void setDozrobienia(String dozrobienia) {
        this.dozrobienia = dozrobienia;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


