package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodLicznik generated by hbm2java
 */
public class PjrodLicznik  implements java.io.Serializable {


     private Integer idLicznik;
     private String numer;
     private String opis;
     private int stanPoczatkowy;
     private int dataStanpocz;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodLicznik() {
    }

	
    public PjrodLicznik(int stanPoczatkowy, int dataStanpocz, int created, int lastMod) {
        this.stanPoczatkowy = stanPoczatkowy;
        this.dataStanpocz = dataStanpocz;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodLicznik(String numer, String opis, int stanPoczatkowy, int dataStanpocz, int created, int lastMod, String whoMod) {
       this.numer = numer;
       this.opis = opis;
       this.stanPoczatkowy = stanPoczatkowy;
       this.dataStanpocz = dataStanpocz;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdLicznik() {
        return this.idLicznik;
    }
    
    public void setIdLicznik(Integer idLicznik) {
        this.idLicznik = idLicznik;
    }
    public String getNumer() {
        return this.numer;
    }
    
    public void setNumer(String numer) {
        this.numer = numer;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public int getStanPoczatkowy() {
        return this.stanPoczatkowy;
    }
    
    public void setStanPoczatkowy(int stanPoczatkowy) {
        this.stanPoczatkowy = stanPoczatkowy;
    }
    public int getDataStanpocz() {
        return this.dataStanpocz;
    }
    
    public void setDataStanpocz(int dataStanpocz) {
        this.dataStanpocz = dataStanpocz;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


