package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodDzialka generated by hbm2java
 */
public class PjrodDzialka  implements java.io.Serializable {


     private Integer idDzialka;
     private int idSektor;
     private String numer;
     private int metraz;
     private String zabudowania;
     private String problemy;
     private int wymogi;
     private int aktywna;
     private String opis;
     private String poprzedniwlasciciel;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodDzialka() {
    }

	
    public PjrodDzialka(int idSektor, String numer, int metraz, int wymogi, int aktywna, int created, int lastMod) {
        this.idSektor = idSektor;
        this.numer = numer;
        this.metraz = metraz;
        this.wymogi = wymogi;
        this.aktywna = aktywna;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodDzialka(int idSektor, String numer, int metraz, String zabudowania, String problemy, int wymogi, int aktywna, String opis, String poprzedniwlasciciel, int created, int lastMod, String whoMod) {
       this.idSektor = idSektor;
       this.numer = numer;
       this.metraz = metraz;
       this.zabudowania = zabudowania;
       this.problemy = problemy;
       this.wymogi = wymogi;
       this.aktywna = aktywna;
       this.opis = opis;
       this.poprzedniwlasciciel = poprzedniwlasciciel;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdDzialka() {
        return this.idDzialka;
    }
    
    public void setIdDzialka(Integer idDzialka) {
        this.idDzialka = idDzialka;
    }
    public int getIdSektor() {
        return this.idSektor;
    }
    
    public void setIdSektor(int idSektor) {
        this.idSektor = idSektor;
    }
    public String getNumer() {
        return this.numer;
    }
    
    public void setNumer(String numer) {
        this.numer = numer;
    }
    public int getMetraz() {
        return this.metraz;
    }
    
    public void setMetraz(int metraz) {
        this.metraz = metraz;
    }
    public String getZabudowania() {
        return this.zabudowania;
    }
    
    public void setZabudowania(String zabudowania) {
        this.zabudowania = zabudowania;
    }
    public String getProblemy() {
        return this.problemy;
    }
    
    public void setProblemy(String problemy) {
        this.problemy = problemy;
    }
    public int getWymogi() {
        return this.wymogi;
    }
    
    public void setWymogi(int wymogi) {
        this.wymogi = wymogi;
    }
    public int getAktywna() {
        return this.aktywna;
    }
    
    public void setAktywna(int aktywna) {
        this.aktywna = aktywna;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public String getPoprzedniwlasciciel() {
        return this.poprzedniwlasciciel;
    }
    
    public void setPoprzedniwlasciciel(String poprzedniwlasciciel) {
        this.poprzedniwlasciciel = poprzedniwlasciciel;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


