package pl.pje.jprogs.rod_entity;
// Generated 2013-09-08 22:11:50 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PjrodUlga generated by hbm2java
 */
@Entity
@Table(name="pjrod_ulga"
    ,catalog="rod"
)
public class PjrodUlga  implements java.io.Serializable {


     private Integer idUlga;
     private String nazwa;
     private String opis;
     private int typUlgi;
     private int wartosc;
     private int dataOd;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodUlga() {
    }

	
    public PjrodUlga(String nazwa, int typUlgi, int wartosc, int dataOd, int created, int lastMod) {
        this.nazwa = nazwa;
        this.typUlgi = typUlgi;
        this.wartosc = wartosc;
        this.dataOd = dataOd;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodUlga(String nazwa, String opis, int typUlgi, int wartosc, int dataOd, int created, int lastMod, String whoMod) {
       this.nazwa = nazwa;
       this.opis = opis;
       this.typUlgi = typUlgi;
       this.wartosc = wartosc;
       this.dataOd = dataOd;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_ulga", unique=true, nullable=false)
    public Integer getIdUlga() {
        return this.idUlga;
    }
    
    public void setIdUlga(Integer idUlga) {
        this.idUlga = idUlga;
    }
    
    @Column(name="nazwa", nullable=false, length=128)
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    
    @Column(name="opis", length=256)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    
    @Column(name="typ_ulgi", nullable=false)
    public int getTypUlgi() {
        return this.typUlgi;
    }
    
    public void setTypUlgi(int typUlgi) {
        this.typUlgi = typUlgi;
    }
    
    @Column(name="wartosc", nullable=false)
    public int getWartosc() {
        return this.wartosc;
    }
    
    public void setWartosc(int wartosc) {
        this.wartosc = wartosc;
    }
    
    @Column(name="data_od", nullable=false)
    public int getDataOd() {
        return this.dataOd;
    }
    
    public void setDataOd(int dataOd) {
        this.dataOd = dataOd;
    }
    
    @Column(name="created", nullable=false)
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    
    @Column(name="last_mod", nullable=false)
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    
    @Column(name="who_mod", length=128)
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


