package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodFaktura generated by hbm2java
 */
public class PjrodFaktura  implements java.io.Serializable {


     private Integer idFaktura;
     private String nrFak;
     private int nrLicznika;
     private int opsPrzejsciowa;
     private int opsPrzesyl;
     private int opsDystrybucja;
     private int opzEnergia;
     private int opzSkljak;
     private int opzSieciowa;
     private int dataOd;
     private int dataDo;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodFaktura() {
    }

	
    public PjrodFaktura(String nrFak, int nrLicznika, int opsPrzejsciowa, int opsPrzesyl, int opsDystrybucja, int opzEnergia, int opzSkljak, int opzSieciowa, int dataOd, int dataDo, int created, int lastMod) {
        this.nrFak = nrFak;
        this.nrLicznika = nrLicznika;
        this.opsPrzejsciowa = opsPrzejsciowa;
        this.opsPrzesyl = opsPrzesyl;
        this.opsDystrybucja = opsDystrybucja;
        this.opzEnergia = opzEnergia;
        this.opzSkljak = opzSkljak;
        this.opzSieciowa = opzSieciowa;
        this.dataOd = dataOd;
        this.dataDo = dataDo;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodFaktura(String nrFak, int nrLicznika, int opsPrzejsciowa, int opsPrzesyl, int opsDystrybucja, int opzEnergia, int opzSkljak, int opzSieciowa, int dataOd, int dataDo, int created, int lastMod, String whoMod) {
       this.nrFak = nrFak;
       this.nrLicznika = nrLicznika;
       this.opsPrzejsciowa = opsPrzejsciowa;
       this.opsPrzesyl = opsPrzesyl;
       this.opsDystrybucja = opsDystrybucja;
       this.opzEnergia = opzEnergia;
       this.opzSkljak = opzSkljak;
       this.opzSieciowa = opzSieciowa;
       this.dataOd = dataOd;
       this.dataDo = dataDo;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdFaktura() {
        return this.idFaktura;
    }
    
    public void setIdFaktura(Integer idFaktura) {
        this.idFaktura = idFaktura;
    }
    public String getNrFak() {
        return this.nrFak;
    }
    
    public void setNrFak(String nrFak) {
        this.nrFak = nrFak;
    }
    public int getNrLicznika() {
        return this.nrLicznika;
    }
    
    public void setNrLicznika(int nrLicznika) {
        this.nrLicznika = nrLicznika;
    }
    public int getOpsPrzejsciowa() {
        return this.opsPrzejsciowa;
    }
    
    public void setOpsPrzejsciowa(int opsPrzejsciowa) {
        this.opsPrzejsciowa = opsPrzejsciowa;
    }
    public int getOpsPrzesyl() {
        return this.opsPrzesyl;
    }
    
    public void setOpsPrzesyl(int opsPrzesyl) {
        this.opsPrzesyl = opsPrzesyl;
    }
    public int getOpsDystrybucja() {
        return this.opsDystrybucja;
    }
    
    public void setOpsDystrybucja(int opsDystrybucja) {
        this.opsDystrybucja = opsDystrybucja;
    }
    public int getOpzEnergia() {
        return this.opzEnergia;
    }
    
    public void setOpzEnergia(int opzEnergia) {
        this.opzEnergia = opzEnergia;
    }
    public int getOpzSkljak() {
        return this.opzSkljak;
    }
    
    public void setOpzSkljak(int opzSkljak) {
        this.opzSkljak = opzSkljak;
    }
    public int getOpzSieciowa() {
        return this.opzSieciowa;
    }
    
    public void setOpzSieciowa(int opzSieciowa) {
        this.opzSieciowa = opzSieciowa;
    }
    public int getDataOd() {
        return this.dataOd;
    }
    
    public void setDataOd(int dataOd) {
        this.dataOd = dataOd;
    }
    public int getDataDo() {
        return this.dataDo;
    }
    
    public void setDataDo(int dataDo) {
        this.dataDo = dataDo;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


