package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodWplata generated by hbm2java
 */
public class PjrodWplata  implements java.io.Serializable {


     private Integer idWplata;
     private int idDzialka;
     private int idFundusz;
     private String wplacajacy;
     private String operacja;
     private int data;
     private int kwota;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodWplata() {
    }

	
    public PjrodWplata(int idDzialka, int idFundusz, int data, int kwota, int created, int lastMod) {
        this.idDzialka = idDzialka;
        this.idFundusz = idFundusz;
        this.data = data;
        this.kwota = kwota;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodWplata(int idDzialka, int idFundusz, String wplacajacy, String operacja, int data, int kwota, int created, int lastMod, String whoMod) {
       this.idDzialka = idDzialka;
       this.idFundusz = idFundusz;
       this.wplacajacy = wplacajacy;
       this.operacja = operacja;
       this.data = data;
       this.kwota = kwota;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdWplata() {
        return this.idWplata;
    }
    
    public void setIdWplata(Integer idWplata) {
        this.idWplata = idWplata;
    }
    public int getIdDzialka() {
        return this.idDzialka;
    }
    
    public void setIdDzialka(int idDzialka) {
        this.idDzialka = idDzialka;
    }
    public int getIdFundusz() {
        return this.idFundusz;
    }
    
    public void setIdFundusz(int idFundusz) {
        this.idFundusz = idFundusz;
    }
    public String getWplacajacy() {
        return this.wplacajacy;
    }
    
    public void setWplacajacy(String wplacajacy) {
        this.wplacajacy = wplacajacy;
    }
    public String getOperacja() {
        return this.operacja;
    }
    
    public void setOperacja(String operacja) {
        this.operacja = operacja;
    }
    public int getData() {
        return this.data;
    }
    
    public void setData(int data) {
        this.data = data;
    }
    public int getKwota() {
        return this.kwota;
    }
    
    public void setKwota(int kwota) {
        this.kwota = kwota;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


