package pl.pje.jprogs.rod_entity;
// Generated 2013-01-06 23:07:07 by Hibernate Tools 3.2.1.GA



/**
 * PjrodUlga generated by hbm2java
 */
public class PjrodUlga  implements java.io.Serializable {


     private Integer idUlga;
     private String nazwa;
     private String opis;
     private int typUlgi;
     private int wartosc;
     private int dataOd;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodUlga() {
    }

	
    public PjrodUlga(String nazwa, int typUlgi, int wartosc, int dataOd, int created, int lastMod) {
        this.nazwa = nazwa;
        this.typUlgi = typUlgi;
        this.wartosc = wartosc;
        this.dataOd = dataOd;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodUlga(String nazwa, String opis, int typUlgi, int wartosc, int dataOd, int created, int lastMod, String whoMod) {
       this.nazwa = nazwa;
       this.opis = opis;
       this.typUlgi = typUlgi;
       this.wartosc = wartosc;
       this.dataOd = dataOd;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
    public Integer getIdUlga() {
        return this.idUlga;
    }
    
    public void setIdUlga(Integer idUlga) {
        this.idUlga = idUlga;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public int getTypUlgi() {
        return this.typUlgi;
    }
    
    public void setTypUlgi(int typUlgi) {
        this.typUlgi = typUlgi;
    }
    public int getWartosc() {
        return this.wartosc;
    }
    
    public void setWartosc(int wartosc) {
        this.wartosc = wartosc;
    }
    public int getDataOd() {
        return this.dataOd;
    }
    
    public void setDataOd(int dataOd) {
        this.dataOd = dataOd;
    }
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


