package pl.pje.hibernate;
// Generated 2013-09-03 23:49:33 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PjrodDzialka generated by hbm2java
 */
@Entity
@Table(name="pjrod_dzialka"
    ,catalog="rod"
)
public class PjrodDzialka  implements java.io.Serializable {


     private Integer idDzialka;
     private int idSektor;
     private String numer;
     private int metraz;
     private String zabudowania;
     private String problemy;
     private int wymogi;
     private int aktywna;
     private String opis;
     private String poprzedniwlasciciel;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodDzialka() {
    }

	
    public PjrodDzialka(int idSektor, String numer, int metraz, int wymogi, int aktywna, int created, int lastMod) {
        this.idSektor = idSektor;
        this.numer = numer;
        this.metraz = metraz;
        this.wymogi = wymogi;
        this.aktywna = aktywna;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodDzialka(int idSektor, String numer, int metraz, String zabudowania, String problemy, int wymogi, int aktywna, String opis, String poprzedniwlasciciel, int created, int lastMod, String whoMod) {
       this.idSektor = idSektor;
       this.numer = numer;
       this.metraz = metraz;
       this.zabudowania = zabudowania;
       this.problemy = problemy;
       this.wymogi = wymogi;
       this.aktywna = aktywna;
       this.opis = opis;
       this.poprzedniwlasciciel = poprzedniwlasciciel;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_dzialka", unique=true, nullable=false)
    public Integer getIdDzialka() {
        return this.idDzialka;
    }
    
    public void setIdDzialka(Integer idDzialka) {
        this.idDzialka = idDzialka;
    }
    
    @Column(name="id_sektor", nullable=false)
    public int getIdSektor() {
        return this.idSektor;
    }
    
    public void setIdSektor(int idSektor) {
        this.idSektor = idSektor;
    }
    
    @Column(name="numer", nullable=false, length=8)
    public String getNumer() {
        return this.numer;
    }
    
    public void setNumer(String numer) {
        this.numer = numer;
    }
    
    @Column(name="metraz", nullable=false)
    public int getMetraz() {
        return this.metraz;
    }
    
    public void setMetraz(int metraz) {
        this.metraz = metraz;
    }
    
    @Column(name="zabudowania", length=256)
    public String getZabudowania() {
        return this.zabudowania;
    }
    
    public void setZabudowania(String zabudowania) {
        this.zabudowania = zabudowania;
    }
    
    @Column(name="problemy", length=256)
    public String getProblemy() {
        return this.problemy;
    }
    
    public void setProblemy(String problemy) {
        this.problemy = problemy;
    }
    
    @Column(name="wymogi", nullable=false)
    public int getWymogi() {
        return this.wymogi;
    }
    
    public void setWymogi(int wymogi) {
        this.wymogi = wymogi;
    }
    
    @Column(name="aktywna", nullable=false)
    public int getAktywna() {
        return this.aktywna;
    }
    
    public void setAktywna(int aktywna) {
        this.aktywna = aktywna;
    }
    
    @Column(name="opis", length=65535)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    
    @Column(name="poprzedniwlasciciel", length=64)
    public String getPoprzedniwlasciciel() {
        return this.poprzedniwlasciciel;
    }
    
    public void setPoprzedniwlasciciel(String poprzedniwlasciciel) {
        this.poprzedniwlasciciel = poprzedniwlasciciel;
    }
    
    @Column(name="created", nullable=false)
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    
    @Column(name="last_mod", nullable=false)
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    
    @Column(name="who_mod", length=128)
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


