package pl.pje.hibernate;
// Generated 2013-09-03 23:49:33 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PjrodSektor generated by hbm2java
 */
@Entity
@Table(name="pjrod_sektor"
    ,catalog="rod"
)
public class PjrodSektor  implements java.io.Serializable {


     private Integer idSektor;
     private int numer;
     private int idLicznikp;
     private int idLicznikw;
     private int metraz;
     private String zabudowy;
     private String problemy;
     private String adres;
     private String gospodarz;
     private String dozrobienia;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodSektor() {
    }

	
    public PjrodSektor(int numer, int idLicznikp, int idLicznikw, int metraz, int created, int lastMod) {
        this.numer = numer;
        this.idLicznikp = idLicznikp;
        this.idLicznikw = idLicznikw;
        this.metraz = metraz;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodSektor(int numer, int idLicznikp, int idLicznikw, int metraz, String zabudowy, String problemy, String adres, String gospodarz, String dozrobienia, int created, int lastMod, String whoMod) {
       this.numer = numer;
       this.idLicznikp = idLicznikp;
       this.idLicznikw = idLicznikw;
       this.metraz = metraz;
       this.zabudowy = zabudowy;
       this.problemy = problemy;
       this.adres = adres;
       this.gospodarz = gospodarz;
       this.dozrobienia = dozrobienia;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_sektor", unique=true, nullable=false)
    public Integer getIdSektor() {
        return this.idSektor;
    }
    
    public void setIdSektor(Integer idSektor) {
        this.idSektor = idSektor;
    }
    
    @Column(name="numer", nullable=false)
    public int getNumer() {
        return this.numer;
    }
    
    public void setNumer(int numer) {
        this.numer = numer;
    }
    
    @Column(name="id_licznikp", nullable=false)
    public int getIdLicznikp() {
        return this.idLicznikp;
    }
    
    public void setIdLicznikp(int idLicznikp) {
        this.idLicznikp = idLicznikp;
    }
    
    @Column(name="id_licznikw", nullable=false)
    public int getIdLicznikw() {
        return this.idLicznikw;
    }
    
    public void setIdLicznikw(int idLicznikw) {
        this.idLicznikw = idLicznikw;
    }
    
    @Column(name="metraz", nullable=false)
    public int getMetraz() {
        return this.metraz;
    }
    
    public void setMetraz(int metraz) {
        this.metraz = metraz;
    }
    
    @Column(name="zabudowy", length=256)
    public String getZabudowy() {
        return this.zabudowy;
    }
    
    public void setZabudowy(String zabudowy) {
        this.zabudowy = zabudowy;
    }
    
    @Column(name="problemy", length=256)
    public String getProblemy() {
        return this.problemy;
    }
    
    public void setProblemy(String problemy) {
        this.problemy = problemy;
    }
    
    @Column(name="adres", length=256)
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    
    @Column(name="gospodarz", length=256)
    public String getGospodarz() {
        return this.gospodarz;
    }
    
    public void setGospodarz(String gospodarz) {
        this.gospodarz = gospodarz;
    }
    
    @Column(name="dozrobienia", length=65535)
    public String getDozrobienia() {
        return this.dozrobienia;
    }
    
    public void setDozrobienia(String dozrobienia) {
        this.dozrobienia = dozrobienia;
    }
    
    @Column(name="created", nullable=false)
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    
    @Column(name="last_mod", nullable=false)
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    
    @Column(name="who_mod", length=128)
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


