package pl.pje.hibernate;
// Generated 2013-09-03 23:49:33 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PjrodLicznik generated by hbm2java
 */
@Entity
@Table(name="pjrod_licznik"
    ,catalog="rod"
)
public class PjrodLicznik  implements java.io.Serializable {


     private Integer idLicznik;
     private String numer;
     private String opis;
     private int stanPoczatkowy;
     private int dataStanpocz;
     private int created;
     private int lastMod;
     private String whoMod;

    public PjrodLicznik() {
    }

	
    public PjrodLicznik(int stanPoczatkowy, int dataStanpocz, int created, int lastMod) {
        this.stanPoczatkowy = stanPoczatkowy;
        this.dataStanpocz = dataStanpocz;
        this.created = created;
        this.lastMod = lastMod;
    }
    public PjrodLicznik(String numer, String opis, int stanPoczatkowy, int dataStanpocz, int created, int lastMod, String whoMod) {
       this.numer = numer;
       this.opis = opis;
       this.stanPoczatkowy = stanPoczatkowy;
       this.dataStanpocz = dataStanpocz;
       this.created = created;
       this.lastMod = lastMod;
       this.whoMod = whoMod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_licznik", unique=true, nullable=false)
    public Integer getIdLicznik() {
        return this.idLicznik;
    }
    
    public void setIdLicznik(Integer idLicznik) {
        this.idLicznik = idLicznik;
    }
    
    @Column(name="numer", length=64)
    public String getNumer() {
        return this.numer;
    }
    
    public void setNumer(String numer) {
        this.numer = numer;
    }
    
    @Column(name="opis", length=128)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    
    @Column(name="stan_poczatkowy", nullable=false)
    public int getStanPoczatkowy() {
        return this.stanPoczatkowy;
    }
    
    public void setStanPoczatkowy(int stanPoczatkowy) {
        this.stanPoczatkowy = stanPoczatkowy;
    }
    
    @Column(name="data_stanpocz", nullable=false)
    public int getDataStanpocz() {
        return this.dataStanpocz;
    }
    
    public void setDataStanpocz(int dataStanpocz) {
        this.dataStanpocz = dataStanpocz;
    }
    
    @Column(name="created", nullable=false)
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    
    @Column(name="last_mod", nullable=false)
    public int getLastMod() {
        return this.lastMod;
    }
    
    public void setLastMod(int lastMod) {
        this.lastMod = lastMod;
    }
    
    @Column(name="who_mod", length=128)
    public String getWhoMod() {
        return this.whoMod;
    }
    
    public void setWhoMod(String whoMod) {
        this.whoMod = whoMod;
    }




}


